import UserNavbar from "@/components/UserNavbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AsideMenuBar from "@/components/AsideMenuBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <UserNavbar />
        <div className="flex container mx-auto">
          <AsideMenuBar />
          <div className="w-full px-4 pt-8">{children}</div>
        </div>
      </body>
    </html>
  );
}
